version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: celery-docker-redis-message-queue
    volumes:
      - ./application:/application
  celeryworker:
    build: .
    command: python -m celery worker --app="application.celery:app" --workdir=/application --queues celery-docker-queue --loglevel=info
    depends_on:
      - redis
    environment:
      - PORTHOLE_CONFIG=${PORTHOLE_CONFIG}
    volumes:
      - ./application:/application
      - ${REPORT_PATH}:/reports
    container_name: celery-docker-celeryworker
  celerybeat:
    build: .
    command: celery beat --app="application.celery:app" --workdir=/ --loglevel=debug
    depends_on:
      - redis
    environment:
      - PORTHOLE_CONFIG=${PORTHOLE_CONFIG}
    volumes:
      - ./application:/application
      - ${REPORT_PATH}:/reports
    container_name: celery-docker-celerybeat
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
      - FLOWER_PORT=8888
    depends_on:
      - redis
    ports:
      - 8888:8888
    container_name: celery-docker-flower
